name: Upload s3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: Deploy index S3
      run: aws s3 cp index.html ${{ secrets.AWS_S3_BUCKET }}
    - name: Deploy css
      run: aws s3 cp style.css ${{ secrets.AWS_S3_BUCKET }}
    - name: Deploy favicon
      run: aws s3 cp favicon.ico ${{ secrets.AWS_S3_BUCKET }}
    - name: Invalidate Cloudfront distro
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
